import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Menu from "./Menu/page";
import { FaArrowRight, FaArrowLeft } from "react-icons/fa";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  // viewport: {
  //   width: 'device-width',
  //   initialScale: 1,
  // },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className={`${inter.className}`}>
        <div className="flex h-screen ">
          <div
            id="header"
            className="w-1/4 h-screen"
            style={{ backgroundColor: "#f5f5f5" }}
          >
            <button></button>
            <Menu />
          </div>
          <div id="content" className="w-3/4 h-screen">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
